/*
 * Copyright (c) 2015-2020, Infineon Technologies AG
 * All rights reserved.                        
 *                                             
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *                                                                              
 * To improve the quality of the software, users are encouraged to share 
 * modifications, enhancements or bug fixes with Infineon Technologies AG 
 * at XMCSupport@infineon.com.
 *
 */

 /**
 * @file MCI.h
 * @date 30 June, 2016
 * @version 1.0
 *
 * @brief MCI/SDMMC Driver for Infineon XMC devices
 *
 * History
 *
 * Version 1.0 Initial version<br>
 */

#ifndef MCI_H
#define MCI_H

/***************************************************************************
 * HEADER FILES
 ***************************************************************************/
#include "xmc_scu.h"
#include "xmc_gpio.h"
#include "xmc_sdmmc.h"

#include "Driver_MCI.h"
#include "RTE_Components.h"
#include "RTE_Device.h"

/***************************************************************************
 *  MACROS
 ***************************************************************************/
#if (defined(RTE_Drivers_MCI) && \
    (RTE_SDMMC0 == 0))
#error "SDMMC not configured in RTE_Device.h!"
#endif

/* Card detect change event enable */
#if (RTE_SDMMC_CD_EVENT_EN == 0)
#define MCI_CD_EVENT           0U
#else
#define MCI_CD_EVENT           1U
#endif

/* Card detect pin enable */
#if (RTE_SDMMC_CD_PIN_EN == 0)
#define MCI_CD_PIN             0U
#else
#define MCI_CD_PIN             1U
#endif

/* write Protect detect pin enable */
#if (RTE_SDMMC_WP_PIN_EN == 0)
#define MCI_WP_PIN             0U
#else
#define MCI_WP_PIN             1U
#endif

/* SDMMC Power pin enable */
#if (RTE_SDMMC_PWR_PIN_EN == 0)
#define MCI_PWR_PIN            0U
#else
#define MCI_PWR_PIN            1U
#endif

/* SDMMC Power pin enable */
#if (RTE_SDMMC_RESET_PIN_EN == 0)
#define MCI_RESET_PIN          0U
#else
#define MCI_RESET_PIN          1U
#endif

/* Enable Bus width of four line */
#if (RTE_SDMMC_BUS_WIDTH_4 == 0)
#define MCI_BUS_WIDTH_4        0U
#else
#define MCI_BUS_WIDTH_4        1U
#endif

/* Transfer event mask */
#define MCI_TRANSFER_EVENT_Msk    (ARM_MCI_EVENT_TRANSFER_ERROR   |\
                                   ARM_MCI_EVENT_TRANSFER_TIMEOUT |\
                                   ARM_MCI_EVENT_TRANSFER_COMPLETE)

/* Command event mask */
#define MCI_COMMAND_EVENT_Msk     (ARM_MCI_EVENT_COMMAND_ERROR   |\
                                   ARM_MCI_EVENT_COMMAND_TIMEOUT |\
                                   ARM_MCI_EVENT_COMMAND_COMPLETE)
/* Expected response flag mask */
#define MCI_RESPONSE_EXPECTED_Msk (ARM_MCI_RESPONSE_SHORT      |\
                                   ARM_MCI_RESPONSE_SHORT_BUSY |\
                                   ARM_MCI_RESPONSE_LONG)

/* SDMMC Default peripheral clock frequncy*/
#define MCI_SDMMC_INT_DEFAULT_CLOCK_IN_HZ  (48000000UL)

/* Normal interrupt status bits*/
#define MCI_NORMAL_INT_STATUS_BITS         (0x7FFFU)

/* Data Buffer ready status- Read or write ready*/
#define MCI_DATA_BUFFER_READY   (((uint32_t)XMC_SDMMC_BUFFER_READ_READY) |\
                                ((uint32_t)XMC_SDMMC_BUFFER_WRITE_READY))

/* Driver flag definitions */
#define MCI_INIT                ((uint8_t)0x01)   /* MCI initialized            */
#define MCI_POWER               ((uint8_t)0x02)   /* MCI powered on& configured */
#define MCI_RESP_LONG           ((uint8_t)0x04)   /* Long response expected     */
#define MCI_DATA_MODE           ((uint8_t)0x08)   /* Data Transfer mode         */
#define MCI_DATA_READ           ((uint8_t)0x10)   /* Read transfer              */
#define MCI_DATA_WRITE          ((uint8_t)0x20)   /* Writetransfer              */

/***************************************************************************
 * ENUMERATIONS
 ***************************************************************************/
/**
 * @brief Data transfer direction
 */
typedef enum MCI_DATA_TRANSFER_DIR {
  MCI_DATA_TRANSFER_READ_BUFFER = 1U,     /**< Read from card */
  MCI_DATA_TRANSFER_WRITE_BUFFER          /**< Write to card */
} MCI_DATA_TRANSFER_DIR_t;

/***************************************************************************
 * DATA STRUCTURES
 ***************************************************************************/
/**
 * @brief MCI GPIO configuration
 */
typedef struct MCI_GPIO_CONFIG {
  XMC_GPIO_CONFIG_t config;               /**< Pin configuration structure*/
  XMC_GPIO_HWCTRL_t hw_control;           /**< HW control setting for pins*/
} MCI_GPIO_CONFIG_t;

/**
 * @brief MCI pin configuration
 */
typedef struct MCI_PIN_CONFIG {
  XMC_GPIO_PORT_t *const port;            /**< Pointer to the GPIO port base address*/
  const uint8_t pin;                      /**< Pin number in the port*/
  const MCI_GPIO_CONFIG_t *config;        /**< Reference to pin configuration structure*/
} MCI_PIN_CONFIG_t;

/**
 * @brief MCI Data Transfer Information
 */
typedef struct MCI_DATAXFER {
  uint32_t *buf;                          /* Data buffer*/
  MCI_DATA_TRANSFER_DIR_t transfer_mode;  /* Data Transfer mode*/
  uint32_t block_cnt;                     /* No of data blocks to transfer*/
  uint32_t block_size;                    /* Blocks size in transfer*/
  uint32_t block_no_quadlets;             /* Block size in quad bytes, total bytes diveded by 4( word size)*/
} MCI_DATAXFER_t;

/**
 * @brief MCI Transfer Information, Master structure
 */
typedef struct MCI_TRANSFER_INFO {
  ARM_MCI_STATUS         status;          /* MCI Driver status*/
  ARM_MCI_SignalEvent_t  cb_event;        /* Driver event callback function*/
  uint32_t               *response;       /* Pointer to response buffer*/
  MCI_DATAXFER_t         dataxfer;        /* Data Transfer Information*/
  uint8_t volatile       flags;           /* Driver state flags*/
} MCI_TRANSFER_INFO_t;

#endif /* MCI_H */

